### ISSUE TITLE
Platform autodetection fails on ARM

### ISSUE THREAD

**Issue by georgebisbas** [devitocodes/devito#1043]
Probably raised after merging #1032, ARM platform autodetection seems to be failing on ISAMBARD's ARMs.
Tested on Cavium ThunderX2 ARM v8.1, with Devito 4.
TO reproduce follow the wiki for installing Devito on ARM.
Needs to work on archinfo.py

**Comment by ggorman** [comment]
Linked to #1106

**Comment by georgebisbas** [comment]
Some more info as I spent half an hour on EPSRC systems, due to some work I had to revive on KNL and SKL. 
Cavium ThunderX2 ARM v8.1 doesn't like '/proc/cpuinfo' but only 'cpuinfo'.
Other than that, which can be fixed, the generated code is not compiled due to :
```
AutoTuner: could not perform any runs
/tmp/devito-jitcache-uid415400263/a81515abc891d92252f8d8962642a2ccea3b9659.c:5:10: fatal error: xmmintrin.h: No such file or directory
 #include "xmmintrin.h"
          ^~~~~~~~~~~~~
compilation terminated.
FAILED compiler invocation:gcc -O3 -g -march=native -fPIC -Wall -std=c99 -shared /tmp/devito-jitcache-uid415400263/a81515abc891d92252f8d8962642a2ccea3b9659.c -lm -o /tmp/devito-jitcache-uid415400263/a81515abc891d92252f8d8962642a2ccea3b9659.so

```

More uncomfortable than that, is that the generated code cannot be found in the related path,
to play with backdoor. 
Just my 2 pennies on an update to this issue, as I was tempted out of nowhere to give a try.

Also updated the wiki as we do not need devitobench anymore. (https://github.com/devitocodes/devito/wiki/%5BManual%5D-Installing-Devito-on-ARM.-Tested-on-GW4-Isambard)

**Comment by georgebisbas** [comment]
Update on v4.2.
Compiler still doesn;t like 
```
 #include "xmmintrin.h"
 #include "pmmintrin.h"
```

Doesnt like
`MM_FLUSH ***`
..
will update more

**Comment by stuartm-dugeo** [comment]
```
diff --git a/devito/passes/iet/misc.py b/devito/passes/iet/misc.py
index 14c2dc7..0b6d3c5 100644
--- a/devito/passes/iet/misc.py
+++ b/devito/passes/iet/misc.py
@@ -24,8 +24,9 @@ def avoid_denormals(iet):
     header = (cgen.Comment('Flush denormal numbers to zero in hardware'),
               cgen.Statement('_MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON)'),
               cgen.Statement('_MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON)'))
-    iet = iet._rebuild(body=(List(header=header),) + iet.body)
-    return iet, {'includes': ('xmmintrin.h', 'pmmintrin.h')}
+    #iet = iet._rebuild(body=(List(header=header),) + iet.body)
+    #return iet, {'includes': ('xmmintrin.h', 'pmmintrin.h')}
+    return iet, {}


 @iet_pass
```

**Comment by georgebisbas** [comment]
Hi @stuartm-dugeo.  Is that a solution or what?

**Comment by stuartm-dugeo** [comment]
After this change, I was able to run devito on an A64FX system (it removes the xmmintrin.h from the source files).

They appear to be there to cause denormalised numbers to be set to zero in hardware - so possibly not that important?

**Comment by stuartm-dugeo** [comment]
FWIW its a quick'n'dirty hack...

**Comment by georgebisbas** [comment]
Yes, I see.
The main issue is that a more global-ARM solution needs to be explored. For Cavium ThunderX2 ARM v8.1this still is not enough probably.

**Comment by georgebisbas** [comment]
Thank you very much of course. Would you like to submit a PR on it?

**Comment by georgebisbas** [comment]
After some discussion with @jaimesouza .
```
# 1) In devito/devito/archinfo.py
# I am using the follwing get_cpu_info(), insted of the current (latest master) version
@memoized_func
def get_cpu_info():
    try:
        # On linux, the following should work and is super quick
        cpu_info = {}
        with open('/proc/cpuinfo', 'r') as f:
            lines = f.readlines()
        get = lambda k: [i for i in lines if i.startswith(k)][0].split(':')[1].strip()
        cpu_info['flags'] = get('flags').split()
        cpu_info['brand'] = get('model name')
        # TODO: Other info omitted as currently unused
    except:
        # Fallback: rely on the slower `cpuinfo`
        cpu_info = cpuinfo.get_cpu_info()
    # At this point we have some information about the CPU, but we can't distinguish
    # between physical and logical cores yet, as:
    # 1) `/proc/cpuinfo` isn't as detailed on Power architectures as on Xeons
    # 2) `cpuinfo.get_cpu_info` only gives the logical core count
    # So below we try another approach
    # Detect number of logical cores
    logical = psutil.cpu_count(logical=True)
    if logical:
        cpu_info['logical'] = logical
    else:
        # Never bumped into a platform that make us end up here, yet
        # But we try to cover this case anyway, with `lscpu`
        try:
            cpu_info['logical'] = lscpu()['CPU(s)']
        except KeyError:
            warning("Logical core count autodetection failed")
            cpu_info['logical'] = 1
    # Detect number of physical cores
    physical = psutil.cpu_count(logical=False)
    if physical:
        cpu_info['physical'] = physical
    else:
        # Fallback: we might end up here on more exotic platforms such a Power8
        try:
            cpu_info['physical'] = lscpu()['Core(s) per socket'] * lscpu()['Socket(s)']
        except KeyError:
            warning("Physical core count autodetection failed")
            cpu_info['physical'] = 1
    return cpu_info
# 2) In devito/devito/passes/iet/misc.py
# I had to remove some intel specific headers
header = ()
#header = (cgen.Comment('Flush denormal numbers to zero in hardware'),
#          cgen.Statement('_MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON)'),
#          cgen.Statement('_MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON)'))
iet = iet._rebuild(body=(List(header=header),) + iet.body)
#return iet, {'includes': ('xmmintrin.h', 'pmmintrin.h')}
return iet, {}
```

**Comment by fcannini** [comment]
@georgebisbas In addition to your 2nd edit, I had to remove all occurrences of `-march=native` from `devito/compiler.py` to be able to build version 4.2.3 with GCC 9.2.0. After that, I begin running tests, which resulted in #1500.
